apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-mq-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-mq
spec:
  replicas: 1  # Adjust as needed
  selector:
    matchLabels:
      app: ibm-mq
  template:
    metadata:
      labels:
        app: ibm-mq
    spec:
      containers:
      - name: ibm-mq
        image: ibmcom/mq:latest
        ports:
        - containerPort: 1414
          name: mq-port
        - containerPort: 9443
          name: mq-console-port
        env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_NAME
          value: SIMPLE
        # Add any additional environment variables as needed
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "1"
        # Add volume mounts for persistent storage if needed
      # Add any additional containers or volumes as needed
---

apiVersion: v1
kind: Service
metadata:
  name: ibm-mq-service
spec:
  selector:
    app: ibm-mq
  ports:
  - protocol: TCP
    port: 1414
    targetPort: 1414
  - protocol: TCP
    port: 9443
    targetPort: 9443
